version: "3"

services:
  app:
    image: luismi705/streamlit-ui
    build:
      context: .
      dockerfile: example/Dockerfile
    ports:
      - 8501:8501
    environment:
      DEBUG: ${DEBUG}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
    volumes:
      - ./example/app.py:/app/app.py
      - ./example/.streamlit:/app/.streamlit

  frontend:
    image: luismi705/streamlit-frontend
    build: streamlit_supabase_auth/frontend
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./streamlit_supabase_auth/frontend/public:/frontend/public
      - ./streamlit_supabase_auth/frontend/src:/frontend/src
      - ./streamlit_supabase_auth/frontend/tsconfig.json:/frontend/tsconfig.json