app = "questmind-frontend"

[build]
  dockerfile = "streamlit_supabase_auth/frontend/Dockerfile.frontend"

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    port = "80" # HTTP

  [[services.ports]]
    port = "443" # HTTPS
