app = "questmind-ui"
primary_region = 'mad'

[build]

[env]
  DEBUG = "false" # Set to "true" if needed

[http_service]
internal_port = 8501
force_https = true
auto_start_machines = true
auto_stop_machines = true
min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1