app = "questmind-ui"

[build]
  dockerfile = "example/Dockerfile.ui"

[env]
  DEBUG = "false" # Set to "true" if needed

[[services]]
  internal_port = 8501
  protocol = "tcp"

  [[services.ports]]
    port = "80" # HTTP

  [[services.ports]]
    port = "443" # HTTPS
